services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - aletheialab-it
    command: [ "npm", "start" ]

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - aletheialab-it
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers" ]


networks:
  aletheialab-it:
    name: aletheialab-it
    driver: bridge
