name: Deploy su Server Casalingo (Self-Hosted)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull latest code (via HTTPS + GitHub token)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 🔐 Usa il token integrato per autenticarsi
        run: |
            cd ~/evoluzione/aletheialab.it
            git pull https://x-access-token:${GH_TOKEN}@github.com/LorenzoCalabrese03/aletheialab.it.git main

      - name: Rebuild containers
        run: |
            cd ~/evoluzione/aletheialab.it
            docker compose up -d --build

      - name: Pulisci spazio su disco (immagini e volumi inutilizzati)
        run: docker system prune -af --volumes

      - name: Deploy completed
        run: echo "Deploy completed on aletheialab server."